import "./globals.css";
import { cookies } from "next/headers";
import { ThemeProvider } from "@/app/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import LayoutClient from "@/app/LayoutClient";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "huEMR App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();

  // read both cookies
  const authUserCookie = cookieStore.get("auth_user")?.value;
  const authOrgsCookie = cookieStore.get("auth_orgs")?.value;

  const authUser = authUserCookie ? JSON.parse(authUserCookie) : null;
  const authOrgs = authOrgsCookie ? JSON.parse(authOrgsCookie) : null;

  // combine into one object for ClientLayout
  const initialAuthData = {
    user: authUser?.user || null,
    currentOrganization: authOrgs?.currentOrganization || null,
    personalOrganization: authOrgs?.personalOrganization || null,
    organizations: authOrgs?.organizations || null,
  };

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <LayoutClient initialAuthData={initialAuthData}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </LayoutClient>
        <Toaster />
      </body>
    </html>
  );
}
